### ISSUE TITLE
Wrong site url in the config file

### ISSUE THREAD

**Issue by dpshelio** [anandxkumar/gsoc_blog#1]
This url
https://github.com/anandxkumar/gsoc_blog/blob/79cb06884075170aabf070caf9d1e1836eb49c59/gatsby-config.js#L9
is also shown in OpenAstronomy blog and redirecting users to the wrong place.

**Comment by anandxkumar** [comment]
Thanks, @dpshelio for letting me know! I updated it in the recent [commit](https://github.com/anandxkumar/gsoc_blog/commit/0bc42e5f709b25358fd24d8e7b5dec34bd8279a0).

**Comment by dpshelio** [comment]
👏 It seems the code that grabs the posts run today before you updated it. Let's see whether it notices your changes tomorrow.

**Comment by anandxkumar** [comment]
Yes, it fixed it. Thanks :+1:
